---
- hosts: dbservers
  sudo: yes
  tasks:
  - name: INSTALL MYSQL
    apt: name={{item}} update_cache=yes
    with_items:
      - mysql-server
      - python-mysqldb
  - name: CREATE DATABASE WordPress
    mysql_db: name=wordpress
  - name: CREATE USER FOR DATABASE WordPress
    mysql_user: name=wordpress password=wordpress priv=wordpress.*:ALL host=10.10.10.20
  - name: CONFIG MYSQL For Remote DB
    lineinfile:
      dest=/etc/mysql/my.cnf
      regexp="bind-address"
      line="bind-address = 0.0.0.0"
  - name: RESTART MYSQL Server
    service: name=mysql state=restarted