---
- name: INSTALL MYSQL
  apt: name={{item}} update_cache=yes
  with_items:
    - mysql-server
    - python-mysqldb
- name: CREATE DATABASE WordPress
  mysql_db: name=wordpress
- name: CREATE USER FOR DATABASE WordPress
  mysql_user: name=wordpress password=wordpress priv=wordpress.*:ALL host={{host_client}}
- name: CONFIG MYSQL For Remote DB
  lineinfile:
    dest=/etc/mysql/my.cnf
    regexp="bind-address"
    line="bind-address = 0.0.0.0"
  notify: RESTART MYSQL Server