---
- name: INSTALL APACHE2
  apt: name=apache2 update_cache=yes
- name: CONFIG VIRTUAL HOST WordPress
  lineinfile:
    dest=/etc/apache2/sites-available/000-default.conf
    regexp="DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/wordpress"
- name: INSTALL PHP5
  apt: name={{item}} update_cache=yes
  with_items:
    - php5
    - libapache2-mod-php5
    - php5-mcrypt
    - php5-mysqlnd-ms
- name: DOWNLOAD WordPress
  get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no
- name: EXTRACT WordPress
  unarchive:
    src=/tmp/wordpress.tar.gz
    dest=/var/www/
    copy=no
- name: COPY FILE CONFIG Wordpress
  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php
- name: FILE CONFIG Wordpress
  lineinfile:
    dest=/var/www/wordpress/wp-config.php
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  with_items:
    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', 'wordpress');"}
    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', 'wordpress');"}
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', 'wordpress');"}
    - {'regexp': "define\\('DB_HOST', '(.)+'\\);", 'line': "define('DB_HOST', '{{host_server}}');"}
  notify: RESTART APACHE2